Config-Version: '1.0.1'

Prefix: '&6[&aEssentials&bMini&6] &c>> &f'
Back: true

JoinBoolean: true
JoinMessage: '&aHerzlich Willkommen &6%Player% &aauf dem Server!'
LeaveBoolean: true
LeaveMessage: '&6%Player% &ahat den Server verlassen!'
SaveInventory: false
Backpack: false
SpawnTP: false
SkipNight: false
BedColor: 'BLUE'

LocationsBackup: false

BackupTime: 5
LocationsBackupMessage: false

IgnoreJoinLeave: false

Invsee:
  Owner: true

Limited: false
LimitedHomes:
  Default: 4
  Medium: 8
  Admin: 12

LimitedHomesPermission:
  Default: essentialsmini.sethome.default
  Medium: essentialsmini.sethome.medium
  Admin: essentialsmini.sethome.admin

HomeTP: true

ShowItem: false
ShowCrafting: false
ShowLocation: false

Position: true

JsonFormat: false

BackupMessages: false
SendPlayerUpdateMessage: true
ZeitgesteuerterRestart: 30
ZeitGesteuerterRestartBoolean: false

StartBalance:
  Amount: 1000.0
  Boolean: false

MoneySign:
  Balance: '&b[§6Balance§b]'
  Buy: '&a[§6Buy§a]'
  Sell: '&a[§6Sell§a]'
  Free: '&a[§6Free§a]'

MySQL: false
SQLite: false

PlayerInfoSave: false
OnlineMode: true

Currency:
  Single: '$'
  Multi: '$'
Vanish:
  Message: false
Economy:
  Activate: false
  MaxBalance: 1000000

TeleportInOtherWorld: true

WorldBackup: false

BackupWorldTime: 60

OnlyEssentialsFeatures: true

AFK:
  Time: 120
  Boolean: false
  IsAFK: '&7[Player] is now AFK'
  IsNotAFK: '&7[Player] is no longer AFK'

NotAllowCommand: '&cNope'
AutoDownload: false

ColoredChat: true
ColoredSigns: true

PlayerShop: true

PlayerEvents: false

TeleportDelay: 3